import { createHash } from "crypto";
import { env, isVertexConfigured } from "../shared/env";
import { generateVertexText } from "../shared/vertex";
import { getSetting, MODEL_SETTING_KEYS } from "../shared/settings";
import { logger } from "../shared/logger";
import { redis } from "../shared/redis";
import { QualityGateError } from "../shared/recovery";
import type { GroundedSource } from "./citations";
import { buildGlobalRulesBlock } from "../shared/editorial-rules";
import { buildBriefDirectivesBlock, readBriefSpecs } from "../shared/brief";
import { DEFAULT_EDITORIAL_POLICY, resolveEditorialPolicy, type EditorialPolicy } from "../shared/editorial-policy";

const log = logger.child({ worker: "writing-worker", stage: "sections" });

/**
 * Section-by-section writing (ENHANCEMENT_IMPLEMENTATION_PLAN.md Task 5).
 * Instead of one monolithic 8k-token completion (which degrades
 * mid-document and must be wholly regenerated on any QA failure), the
 * article is decomposed into the mandatory section skeleton, each section
 * generated by an independent Flash-class call, retried individually, and
 * cached in Redis so a stage-level retry only regenerates what failed.
 *
 * The section plan derives from the MANDATORY skeleton (not the outline's
 * free-form sections) so sectioned output is structurally guaranteed to
 * satisfy the writing gate and the quality scorer's requiredSections -
 * outline bullets/FAQs are merged in where they align.
 */

export type SectionKind =
  | "intro"
  | "toc"
  | "generic"
  | "subsections"
  | "steps"
  | "table"
  | "numbered"
  | "bullets"
  | "faq"
  | "cta";

export type SubsectionSpec = {
  heading: string;
  discuss?: string[];
  keywords?: string[];
};

export type ComparisonTableSpec = {
  columns: string[];
  rows: string[];
  instructions?: string;
};

export type SectionSpec = {
  /** H2 text; null only for the heading-less intro. */
  heading: string | null;
  kind: SectionKind;
  intent: string;
  bullets: string[];
  wordTarget: number;
  subsections?: SubsectionSpec[];
  comparisonTable?: ComparisonTableSpec;
  /**
   * Brief-supplied section directives (outlineJson.sections[]): the question
   * this section answers, what it must not do, extra requirements, the
   * evidence bar, an illustrative scenario, a required output format, and a
   * link the section has to carry.
   */
  readerQuestion?: string;
  avoid?: string[];
  requirements?: string[];
  evidenceRequirements?: string[];
  practicalExample?: string;
  format?: string;
  requiredInternalLink?: { url: string; anchor?: string };
  /** FAQ questions that must be emitted as H3 entries with answers. */
};

export type SectionArticleContext = {
  title: string;
  topic: string;
  description: string;
  plan?: {
    searchIntent: string;
    audience: string;
    angle: string;
    primaryKeyword: string;
    secondaryKeywords: unknown;
    competitorNotes: unknown;
  };
  outline?: { sections: unknown; faqs: unknown };
  sources?: GroundedSource[];
  /** Digest of the submission's reference sources; empty for unsourced briefs. */
  evidenceSummary?: string;
  /** Rotated per section so legacy articles cite more than one source. */
  preferredEvidenceUrl?: string;
  keywords: string[];
  /**
   * BlogInput.focusKeyword. The article contract requires it verbatim in the
   * introduction, and the intro is written as its own section here, so the
   * requirement has to travel with the section context.
   */
  focusKeyword?: string;
  /** Resolved editorial policy - see shared/editorial-policy.ts. */
  policy?: EditorialPolicy;
  /** Brief requirements with no column of their own - see shared/brief.ts. */
  briefDirectives?: string[];
  /** generationConfig.maxSectionRetries - attempts per section (default 2). */
  maxSectionRetries?: number;
  /** BlogInput.tone - professional | casual | technical. */
  tone?: string;
  /** BlogInput.contentLength - the editor's target word count for the article. */
  targetWords?: number;
  /** Binding article-wide range from the brief. */
  /** Full submission specs (writingInstructions, internalLinks, etc.) */
  specs?: Record<string, unknown>;
  internalLinks?: string[];
  writingInstructions?: string[];
  mustFollow?: string[];
};

export const DEFAULT_MUST_FOLLOW_RULES: string[] = [
  "Generate every section defined in the outline in the exact specified order.",
  "Do not skip, merge, or rename sections unless explicitly instructed.",
  "Treat the requested word count as a guide, not a quota - never pad a section with filler or repeated explanation to reach it.",
  "Include every required comparison table, code example, FAQ, and conclusion.",
  "Do not stop generation until all outline sections have been completed.",
  "Never end a section or article mid-sentence.",
  "Ensure every heading in the outline appears in the final article.",
  "Ensure every FAQ question has a complete answer.",
  "Verify factual claims against the provided evidence sources.",
  "Do not invent benchmark results or unsupported technical claims.",
  "Use SEO keywords naturally without keyword stuffing.",
  "Before returning the article, verify that all required sections are present and complete.",
];

export type SectionDraft = {
  heading: string | null;
  markdown: string;
  usage: { promptTokens: number; completionTokens: number };
  model: string;
  fromCache: boolean;
};

type OutlineSectionLike = {
  heading?: unknown;
  intent?: unknown;
  bullets?: unknown;
  wordTarget?: unknown;
  claims?: unknown;
  subsections?: unknown;
  paragraphs?: unknown;
  comparisonTable?: unknown;
  readerQuestion?: unknown;
  avoid?: unknown;
  requirements?: unknown;
  evidenceRequirements?: unknown;
  practicalExample?: unknown;
  format?: unknown;
  requiredInternalLink?: unknown;
};

/** The brief's per-section directives, as the section plan carries them. */
function sectionDirectives(section: OutlineSectionLike): Partial<SectionSpec> {
  const list = (value: unknown): string[] | undefined => {
    if (!Array.isArray(value)) return undefined;
    const items = value.map(String).map((item) => item.trim()).filter(Boolean);
    return items.length > 0 ? items : undefined;
  };
  const text = (value: unknown): string | undefined => (typeof value === "string" && value.trim() ? value.trim() : undefined);
  const link =
    section.requiredInternalLink && typeof section.requiredInternalLink === "object"
      ? (section.requiredInternalLink as { url?: unknown; anchor?: unknown })
      : null;

  return {
    readerQuestion: text(section.readerQuestion),
    avoid: list(section.avoid),
    requirements: list(section.requirements),
    evidenceRequirements: list(section.evidenceRequirements),
    practicalExample: text(section.practicalExample),
    format: text(section.format),
    requiredInternalLink: link && text(link.url) ? { url: String(link.url), anchor: text(link.anchor) } : undefined,
  };
}
type OutlineFaqLike = { question?: unknown; answerIntent?: unknown };

/* ------------------------------------------------------------------ */
/* Section plan                                                        */
/* ------------------------------------------------------------------ */

/**
 * Fallback spine, used only when no outline reached the writer. Deliberately
 * short: the old 14-section skeleton forced "Key Features", "Benefits",
 * "Pros and Cons" and "Real World Use Cases" into every article, which is
 * where most duplicate-explanation and padding came from. An outline-driven
 * article never uses this - buildSectionPlan follows the outline instead.
 */
function skeletonWords(total: number, policy: EditorialPolicy) {
  const weights: [string | null, SectionKind, number][] = [
    [null, "intro", 0.1],
    ...(policy.tableOfContents ? ([["Table of Contents", "toc", 0.02]] as [string, SectionKind, number][]) : []),
    ["What is {topic}?", "generic", 0.16],
    ["How it works", "steps", 0.22],
    ["Implementation guidance", "subsections", 0.22],
    ["Trade-offs and common mistakes", "bullets", 0.14],
    ["FAQs", "faq", 0.1],
    ["Conclusion", "generic", 0.06],
  ];
  return weights.map(([heading, kind, share]) => ({
    heading,
    kind,
    wordTarget: Math.max(40, Math.round(total * share)),
  }));
}

const DEFAULT_INTENTS: Record<SectionKind, string> = {
  intro: "Explain the topic, the reader's problem, and the practical value of reading on.",
  toc: "Linked table of contents for the article.",
  generic: "Cover the section topic with practical, specific detail.",
  subsections: "Break the topic into named H3 subsections, each with substantial paragraphs explaining mechanisms, architecture, and practical considerations.",
  steps: "Explain the mechanism as 3-4 named H3 steps.",
  table: "Balanced comparison as a Markdown comparison table plus thorough framing and analysis.",
  numbered: "Actionable numbered checklist.",
  bullets: "Common pitfalls as a bullet list with avoidance guidance.",
  faq: "Questions with concise, direct answers.",
  cta: "One short practical call-to-action paragraph related to DevKit Market.",
};

function normalizeHeading(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9 ]/g, "").trim();
}

function requiredFaqQuestions(faqs: OutlineFaqLike[]): string[] {
  return Array.from(new Set(faqs.map((faq) => (typeof faq.question === "string" ? faq.question.trim() : "")).filter(Boolean)));
}

function budgetSectionPlan(plan: SectionSpec[], context: SectionArticleContext): SectionSpec[] {
  const ceiling = (context.wordBounds ?? readBriefSpecs(context.specs).wordBounds)?.max;
  // Stay below a binding ceiling so assembly, FAQ answers, and light editing
  // have room. The brief's maximum remains the final validator's authority.
  const desired = ceiling && ceiling > 0
    ? Math.min(context.targetWords ?? Math.round(ceiling * 0.93), Math.floor(ceiling * 0.93))
    // Models commonly land below a per-section target. For briefs without a
    // ceiling, generate against a 40% larger internal budget so the assembled
    // draft reliably clears its required minimum.
    : context.targetWords ? Math.round(context.targetWords * 1.4) : undefined;
/**
 * Build the section plan. When the editor supplies an outline, use its
 * sections as the canonical article structure. When no outline exists,
 * fall back to the default mandatory skeleton.
 */
export function buildSectionPlan(context: SectionArticleContext): SectionSpec[] {
  const policy = context.policy ?? resolveEditorialPolicy(context.specs);
  const targetTotal =
    context.targetWords && context.targetWords > 0
      ? context.targetWords
      : Math.round((env.BLOG_MIN_WORDS + env.BLOG_MAX_WORDS) / 2);

  const outlineSections: OutlineSectionLike[] = Array.isArray(context.outline?.sections)
    ? (context.outline.sections as OutlineSectionLike[])
    : [];
  const outlineFaqs: OutlineFaqLike[] = Array.isArray(context.outline?.faqs)
    ? (context.outline.faqs as OutlineFaqLike[])
    : [];

  if (outlineSections.length > 0) {
    const firstIsIntro = /intro/i.test(String(outlineSections[0]?.heading ?? ""));
    const plan: SectionSpec[] = [];

    const nonIntroSectionsCount = Math.max(1, outlineSections.length - (firstIsIntro ? 1 : 0));
    const introBudget = Math.max(100, Math.round(targetTotal * 0.08));
    const bodyBudgetPerSection = Math.max(
      120,
      Math.round((targetTotal - introBudget) / nonIntroSectionsCount)
    );

    if (firstIsIntro) {
      const introSec = outlineSections[0];
      const rawSub = (introSec.subsections ?? introSec.paragraphs) as SubsectionSpec[] | undefined;
      const bullets = Array.isArray(introSec.bullets) ? introSec.bullets.map(String).filter(Boolean) : [];
      plan.push({
        heading: null,
        kind: "intro",
        intent: typeof introSec.intent === "string" ? introSec.intent : DEFAULT_INTENTS.intro,
        bullets,
        subsections: rawSub,
        wordTarget: typeof introSec.wordTarget === "number" ? (introSec.wordTarget as number) : introBudget,
        ...sectionDirectives(introSec),
      });
    } else {
      plan.push({
        heading: null,
        kind: "intro",
        intent: DEFAULT_INTENTS.intro,
        bullets: [],
        wordTarget: introBudget,
      });
    }

    // R9: a table of contents only when the submission asked for one.
    if (policy.tableOfContents) {
      plan.push({
        heading: "Table of Contents",
        kind: "toc",
        intent: DEFAULT_INTENTS.toc,
        bullets: [],
        wordTarget: 30,
      });
    }

    const bodySections = firstIsIntro ? outlineSections.slice(1) : outlineSections;
    for (const sec of bodySections) {
      const heading = String(sec.heading ?? "Section");
      const rawSub = (sec.subsections ?? sec.paragraphs) as SubsectionSpec[] | undefined;
      const comparisonTable = sec.comparisonTable as ComparisonTableSpec | undefined;
      const isFaq = /faq|frequently asked/i.test(heading);
      const isConclusion = /conclusion|summary/i.test(heading);

      let kind: SectionKind = "generic";
      if (comparisonTable) {
        kind = "table";
      } else if (isFaq) {
        kind = "faq";
      } else if (/numbered|step.by.step|procedure/.test(format)) {
        kind = "numbered";
      } else if (rawSub && rawSub.length > 0) {
        kind = "subsections";
      } else if (isConclusion) {
        kind = "generic";
      }

      let bullets = Array.isArray(sec.bullets) ? sec.bullets.map(String).filter(Boolean) : [];
      if (isFaq && outlineFaqs.length > 0 && bullets.length === 0) {
        bullets = outlineFaqs
          .map((faq) =>
            typeof faq.question === "string"
              ? `${faq.question}${typeof faq.answerIntent === "string" ? ` - ${faq.answerIntent}` : ""}`
              : null
          )
          .filter((b): b is string => Boolean(b));
      }

      plan.push({
        heading,
        kind,
        intent:
          typeof sec.intent === "string"
            ? sec.intent
            : (DEFAULT_INTENTS[kind] ?? `Cover "${heading}" for the reader in depth.`),
        bullets,
        subsections: rawSub,
        comparisonTable,
        wordTarget: typeof sec.wordTarget === "number" ? (sec.wordTarget as number) : bodyBudgetPerSection,
        ...sectionDirectives(sec),
      });
    }
    if (faqQuestions.length > 0 && !plan.some((section) => section.kind === "faq")) {
  }

  // Fallback: the short spine when no outline is present
  const skeleton = skeletonWords(targetTotal, policy);
  return skeleton.map(({ heading, kind, wordTarget }) => {
    const resolvedHeading = heading?.replace("{topic}", context.topic) ?? null;
    return {
      heading: resolvedHeading,
      kind,
      intent: DEFAULT_INTENTS[kind],
      bullets: [],
      wordTarget,
    };
  });
}

/* ------------------------------------------------------------------ */
/* Section generation                                                  */
/* ------------------------------------------------------------------ */

function sectionTemperature(kind: SectionKind): number {
  if (kind === "steps" || kind === "table" || kind === "faq") return 0.25;
  if (kind === "intro" || kind === "generic") return 0.45;
  return 0.35;
}

function kindInstruction(kind: SectionKind, heading: string | null): string {
  switch (kind) {
    case "intro":
      return "Write the article introduction (2-4 paragraphs). No heading - start directly with prose.";
    case "generic":
      return `Start with exactly "## ${heading}" on its own line, then detailed technical prose.`;
    case "subsections":
      return `Start with "## ${heading}", then create named "### " subsections for each required topic, each with substantial paragraphs explaining mechanisms, architecture, and practical considerations.`;
    case "steps":
      return `Start with "## ${heading}", then 3-4 "### Step N: Name" subsections explaining the mechanism. Include one short fenced code block with a practical command, configuration snippet, or API example.`;
    case "table":
      return `Start with "## ${heading}", introductory framing prose, then the Markdown comparison table (| columns |), followed by explanatory analysis.`;
    case "numbered":
      return `Start with "## ${heading}", then a numbered list ("1. ", "2. ") of actionable practices, each with a paragraph of detail.`;
    case "bullets":
      return `Start with "## ${heading}", then a bullet list ("- " only, never "* ") with avoidance guidance.`;
    case "faq":
      return `Start with "## ${heading || "FAQs"}", then "### " questions, each answered thoroughly with practical technical answers.`;
    case "cta":
      return `Start with "## Call To Action", then one short practical CTA paragraph.`;
    default:
      return "";
  }
}

function buildSectionPrompt(spec: SectionSpec, context: SectionArticleContext, repairNote?: string): string {
  const sources = context.sources ?? [];
  const sourcesBlock =
    sources.length > 0
      ? `
SOURCES (ground truth for factual claims - cite with markers, never URLs):
${sources.map((source) => `${source.marker} ${source.title}\nFACTS:\n${source.evidence.map((fact) => `- ${fact}`).join("\n")}`).join("\n")}
Marker rules: Every specific number, percentage, date, version, benchmark, or empirical fact you draw from SOURCES MUST end with its source marker (e.g. [S1]). Only ${sources.map((s) => s.marker).join(", ")} exist - never invent markers. If no source covers a specific figure, describe it qualitatively instead of fabricating numbers.`
      : "";
  const legacyUrls = Array.from(
    new Set((context.evidenceSummary?.match(/https?:\/\/[^\s)]+/g) ?? []).map((url) => url.replace(/[.,)]+$/, "")))
  );
  const legacyEvidenceBlock =
    sources.length === 0 && legacyUrls.length > 0
      ? `
EVIDENCE URLS (use these exact URLs for factual attribution):
${legacyUrls.map((url) => `- ${url}`).join("\n")}
Citation rules: when this section makes a factual claim about the topic, attach an inline Markdown link to one of the URLs above. Never invent URLs. ${context.preferredEvidenceUrl ? `Use ${context.preferredEvidenceUrl} for at least one supported claim in this section when it fits.` : ""}`
      : "";

  const keywordsBlock =
    context.keywords.length > 0
      ? `\nWeave in these keywords naturally into headings and sentences where relevant: ${context.keywords.join(", ")}.`
      : "";
  const requiredPrimaryBlock = spec.requiredPrimaryKeywords?.length

  // Only the intro section can satisfy the contract's "focus keyword in the
  // introduction" rule - every other section just uses the phrase where it
  // fits. The H1 is not this prompt's job (sections never emit one); vertex.ts
  // enforces it on the assembled article.
  const focusKeyword = context.focusKeyword?.trim();
  const focusKeywordBlock = !focusKeyword
    ? ""
    : spec.kind === "intro"
      ? `\nFocus keyword (mandatory): the FIRST paragraph of this introduction MUST contain the exact phrase "${focusKeyword}" exactly once. Use natural variations after that.`

  let subsectionsBlock = "";
  if (spec.subsections && spec.subsections.length > 0) {
    subsectionsBlock = `
Required Subsections (emit each as "### [Heading]"):
${spec.subsections
  .map((sub) => {
    const discussLines =
      sub.discuss && sub.discuss.length > 0
        ? `\n  Points to discuss in detail:\n${sub.discuss.map((d) => `  - ${d}`).join("\n")}`
        : "";
    const kwLines =
      sub.keywords && sub.keywords.length > 0 ? `\n  Subsection keywords: ${sub.keywords.join(", ")}` : "";
    return `- ### ${sub.heading}${discussLines}${kwLines}`;
  })
  .join("\n")}
`;
  }

  let tableBlock = "";
  if (spec.comparisonTable) {
    tableBlock = `
Required Comparison Table:
Render a detailed Markdown table with columns: | ${spec.comparisonTable.columns.join(" | ")} |
Ensure rows cover: ${spec.comparisonTable.rows.join(", ")}
${spec.comparisonTable.instructions ? `Table instructions: ${spec.comparisonTable.instructions}` : ""}
`;
  }

  const rawSpecs = (context.specs ?? {}) as Record<string, unknown>;
  const nestedSpecs = (rawSpecs.specs ?? {}) as Record<string, unknown>;
  const writingInstructions: string[] =
    context.writingInstructions ??
    (Array.isArray(rawSpecs.writingInstructions)
      ? (rawSpecs.writingInstructions as string[])
      : Array.isArray(nestedSpecs.writingInstructions)
      ? (nestedSpecs.writingInstructions as string[])
      : []);
  const writingInstructionsBlock =
    writingInstructions.length > 0
      ? `\nEditorial Writing Instructions:\n${writingInstructions.map((inst) => `- ${inst}`).join("\n")}\n`
      : "";

  const internalLinks: string[] =
    context.internalLinks ??
    (Array.isArray(rawSpecs.internalLinks)
      ? (rawSpecs.internalLinks as string[])
      : Array.isArray(nestedSpecs.internalLinks)
      ? (nestedSpecs.internalLinks as string[])
      : []);
  const internalLinksBlock =
    internalLinks.length > 0
      ? `\nInternal links to naturally weave into text where contextually appropriate: ${internalLinks.join(", ")}.\n`
      : "";

  const bulletsBlock = spec.bullets.length > 0 ? `\nKey points to cover:\n${spec.bullets.map((bullet) => `- ${bullet}`).join("\n")}` : "";
  const requiredFaqBlock = spec.requiredFaqQuestions?.length

  // The brief's per-section directives. Each is stated separately so the model
  // can act on them individually rather than parsing one long note.
  const directiveLines: string[] = [];
  if (spec.readerQuestion) directiveLines.push(`This section must answer the reader question: "${spec.readerQuestion}"`);
  for (const requirement of spec.requirements ?? []) directiveLines.push(`Requirement: ${requirement}`);
  for (const evidence of spec.evidenceRequirements ?? []) directiveLines.push(`Evidence: ${evidence}`);
  if (spec.practicalExample) directiveLines.push(`Include this practical example: ${spec.practicalExample}`);
  if (spec.format) directiveLines.push(`Format: ${spec.format}`);
  if (spec.requiredInternalLink) {
    directiveLines.push(
      `Include exactly one Markdown link to ${spec.requiredInternalLink.url}${
        spec.requiredInternalLink.anchor ? ` with anchor text "${spec.requiredInternalLink.anchor}"` : ""
      }, placed where it genuinely helps the reader.`
    );
  }
  for (const avoid of spec.avoid ?? []) directiveLines.push(`Do NOT: ${avoid}`);
  const sectionDirectivesBlock =
    directiveLines.length > 0
      ? `\nSection directives (from the brief - binding):\n${directiveLines.map((line) => `- ${line}`).join("\n")}\n`
      : "";

  const briefBlock = buildBriefDirectivesBlock(context.briefDirectives ?? readBriefSpecs(context.specs).directives);
  const repairBlock = repairNote ? `\n${repairNote}\nRewrite the section so the issue is fixed while keeping anything that already worked.` : "";

  const rawGenInst = (rawSpecs.generationInstructions ?? nestedSpecs.generationInstructions) as Record<string, unknown> | undefined;
  const userMustFollow = Array.isArray(rawGenInst?.mustFollow)
    ? (rawGenInst.mustFollow as string[])
    : Array.isArray(context.mustFollow)
    ? context.mustFollow
    : [];
  const mustFollowRules = Array.from(new Set([...DEFAULT_MUST_FOLLOW_RULES, ...userMustFollow]));
  const globalRulesBlock = buildGlobalRulesBlock(context.policy ?? resolveEditorialPolicy(context.specs), context.focusKeyword);
  const mustFollowBlock = `
MANDATORY GENERATION INSTRUCTIONS (MUST FOLLOW):
${mustFollowRules.map((rule, idx) => `${idx + 1}. ${rule}`).join("\n")}
`;

  return `You are a Staff Technical Writer for DevKit Market, a developer-focused tech blog. You are writing ONE SECTION of a larger article - not the whole article.

Article title: "${context.title}"
Topic: "${context.topic}"
${context.plan ? `Audience: ${context.plan.audience}\nAngle: ${context.plan.angle}` : `Context: ${context.description || "none"}`}

Section to write: ${spec.heading ? `"## ${spec.heading}"` : "the introduction"}
Section intent: ${spec.intent}
Target length: at least ${spec.wordTarget} words. Write in depth with rich technical substance. Paragraphs under 100 words each; sentences average 15-20 words.
${kindInstruction(spec.kind, spec.heading)}${subsectionsBlock}${tableBlock}${bulletsBlock}${sectionDirectivesBlock}${keywordsBlock}${focusKeywordBlock}${internalLinksBlock}${writingInstructionsBlock}${briefBlock}${sourcesBlock}${legacyEvidenceBlock}${repairBlock}
${mustFollowBlock}${globalRulesBlock}
Rules:
- GitHub Flavored Markdown. Technical, practical, zero fluff.
- Explain architecture, mechanisms, and developer trade-offs thoroughly.
- For empirical benchmarks, specific quotes, and external claims, cite the supplied SOURCES with markers (e.g. [S1]).
- Avoid unsupported speed rankings or declaring an unqualified "best" framework without evidence.
- Do not invent pricing, adoption statistics, or fake capabilities.
- Output ONLY this section's Markdown - no H1, no commentary, no code fence around the whole section.`;
}

export type GenerateSectionOptions = {
  repairNote?: string;
  modelOverride?: string;
};

/** One section = one Flash-class call. Callers handle retry/caching. */
export async function generateSection(
  spec: SectionSpec,
  context: SectionArticleContext,
  options: GenerateSectionOptions = {}
): Promise<SectionDraft> {
  if (!isVertexConfigured) throw new Error("Vertex AI is not configured");
  const model = options.modelOverride ?? (await getSetting(MODEL_SETTING_KEYS.writingSections, env.VERTEX_FLASH));
  const maxTokens = Math.max(2048, Math.ceil(spec.wordTarget * 4));
  const prompt = buildSectionPrompt(spec, context, options.repairNote);

  let result = await generateVertexText(model, prompt, {
    maxOutputTokens: maxTokens,
    temperature: sectionTemperature(spec.kind),
    timeoutMs: env.WRITING_TIMEOUT_MS,
  });

  // Length check: if generated text is less than 80% of target words
  // (and target >= 100 words), retry once asking for depth. Anything still
  // short is caught by the final article contract before persistence.
  const generatedWords = result.text.trim().split(/\s+/).filter(Boolean).length;
  if (spec.wordTarget >= 100 && generatedWords < Math.round(spec.wordTarget * 0.8)) {
    log.warn(
      `Section "${spec.heading ?? "intro"}" under word target (${generatedWords}/${spec.wordTarget} words) - retrying with expansion`,
      { heading: spec.heading, generatedWords, wordTarget: spec.wordTarget }
    );
    try {
      const expandedResult = await generateVertexText(
        model,
        `${prompt}\n\nIMPORTANT: The previous attempt was too brief (${generatedWords} words). Expand this section with thorough technical analysis, architectural details, and code or comparison points to reach at least ${spec.wordTarget} words.`,
        {
          maxOutputTokens: maxTokens,
          temperature: sectionTemperature(spec.kind),
          timeoutMs: env.WRITING_TIMEOUT_MS,
        }
      );
      if (expandedResult.text.trim().split(/\s+/).filter(Boolean).length > generatedWords) {
        result = expandedResult;
      }
    } catch {
      // Keep original result if expansion retry fails
    }
  }

  return {
    heading: spec.heading,
    markdown: result.text.trim(),
    usage: result.usage,
    model,
    fromCache: false,
  };
}

/* ------------------------------------------------------------------ */
/* Deterministic sections (no model call)                              */
/* ------------------------------------------------------------------ */

function anchorFor(heading: string): string {
  return `#${heading.toLowerCase().replace(/[^a-z0-9\s-]/g, "").replace(/\s+/g, "-")}`;
}

/**
 * The ToC is pure structure - generating it with a model is wasted tokens.
 * Anchor links are opt-in (R9): without them the ToC is a plain list of
 * section names, which is what the global rules ask for.
 */
export function buildTableOfContents(plan: SectionSpec[], policy: EditorialPolicy = DEFAULT_EDITORIAL_POLICY): SectionDraft {
  const links = plan
    .filter((spec): spec is SectionSpec & { heading: string } => spec.heading !== null && spec.kind !== "toc")
    .map((spec) => (policy.anchorLinks ? `- [${spec.heading}](${anchorFor(spec.heading)})` : `- ${spec.heading}`))
    .join("\n");
  return {
    heading: "Table of Contents",
    markdown: `## Table of Contents\n\n${links}`,
    usage: { promptTokens: 0, completionTokens: 0 },
    model: "local",
    fromCache: false,
  };
}

/* ------------------------------------------------------------------ */
/* Parallel execution + retry + Redis cache                            */
/* ------------------------------------------------------------------ */

async function mapWithConcurrency<T, R>(items: T[], concurrency: number, fn: (item: T, index: number) => Promise<R>): Promise<R[]> {
  const results: R[] = new Array(items.length);
  let cursor = 0;
  async function next(): Promise<void> {
    const index = cursor;
    cursor += 1;
    if (index >= items.length) return;
    results[index] = await fn(items[index], index);
    return next();
  }
  await Promise.all(Array.from({ length: Math.min(concurrency, items.length) }, next));
  return results;
}

function cacheKey(blogInputId: string): string {
  // Versioned after custom outline support and rich section prompts.
  return `sections:v3:${blogInputId}`;
}

export async function clearSectionCache(blogInputId: string): Promise<void> {
  try {
    await redis.del(cacheKey(blogInputId));
  } catch (error) {
    log.warn("Section cache invalidation failed", { blogInputId, error: error instanceof Error ? error.message : String(error) });
  }
}

/** Inputs that must match for a cached section to be reused on retry. */
function inputsHash(plan: SectionSpec[], context: SectionArticleContext): string {
  return createHash("sha256")
    .update(
      JSON.stringify({
        headings: plan.map((spec) => spec.heading),
        title: context.title,
        sources: (context.sources ?? []).map((source) => source.marker),
        evidenceUrls: Array.from(new Set((context.evidenceSummary?.match(/https?:\/\/[^\s)]+/g) ?? []).map((url) => url.replace(/[.,)]+$/, "")))),
        min: env.BLOG_MIN_WORDS,
        max: env.BLOG_MAX_WORDS,
        wordBounds: context.wordBounds,
        targetWords: context.targetWords,
      })
    )
    .digest("hex")
    .slice(0, 16);
}

type CachedSections = { inputsHash: string; sections: Record<string, { markdown: string; model: string }> };

const CACHE_TTL_SECONDS = 3600;

/**
 * Generate every model-backed section of the plan with bounded parallelism,
 * one in-call retry per section, and a 1h Redis cache keyed on the section
 * inputs - a BullMQ retry of the whole stage then only regenerates the
 * sections that failed, instead of paying for a full redraft.
 */
export async function generateAllSections(
  plan: SectionSpec[],
  context: SectionArticleContext,
  blogInputId: string
): Promise<{ drafts: SectionDraft[]; usage: { promptTokens: number; completionTokens: number }; models: string[] }> {
  const hash = inputsHash(plan, context);
  let cached: CachedSections | null = null;
  try {
    const raw = await redis.get(cacheKey(blogInputId));
    if (raw) {
      const parsed = JSON.parse(raw) as CachedSections;
      if (parsed.inputsHash === hash) cached = parsed;
    }
  } catch (error) {
    log.warn("Section cache read failed, generating uncached", { error: error instanceof Error ? error.message : String(error) });
  }

  const usage = { promptTokens: 0, completionTokens: 0 };
  const models = new Set<string>();
  const newCache: CachedSections = { inputsHash: hash, sections: {} };

  const legacyUrls = Array.from(
    new Set((context.evidenceSummary?.match(/https?:\/\/[^\s)]+/g) ?? []).map((url) => url.replace(/[.,)]+$/, "")))
  );
  const drafts = await mapWithConcurrency(plan, env.WRITING_SECTION_CONCURRENCY, async (spec, index): Promise<SectionDraft> => {
    if (spec.kind === "toc") return buildTableOfContents(plan, context.policy ?? resolveEditorialPolicy(context.specs));

    const cacheId = spec.heading ?? "__intro__";
    const hit = cached?.sections[cacheId];
    if (hit) {
      models.add(hit.model);
      return { heading: spec.heading, markdown: hit.markdown, usage: { promptTokens: 0, completionTokens: 0 }, model: hit.model, fromCache: true };
    }

    let lastError: unknown;
    const maxAttempts = context.maxSectionRetries ?? readBriefSpecs(context.specs).maxSectionRetries ?? 2;
    for (let attempt = 1; attempt <= maxAttempts; attempt += 1) {
      try {
        const draft = await generateSection(spec, {
          ...context,
          preferredEvidenceUrl: legacyUrls.length > 0 ? legacyUrls[index % legacyUrls.length] : undefined,
        });
        usage.promptTokens += draft.usage.promptTokens;
        usage.completionTokens += draft.usage.completionTokens;
        models.add(draft.model);
        newCache.sections[cacheId] = { markdown: draft.markdown, model: draft.model };
        return draft;
      } catch (error) {
        lastError = error;
        log.warn(`Section "${spec.heading ?? "intro"}" generation attempt ${attempt} failed`, {
          error: error instanceof Error ? error.message : String(error),
        });
      }
    }
    throw new QualityGateError({
      stage: "writing-worker",
      score: 0,
      passed: false,
      reasons: [
        `Section "${spec.heading ?? "Introduction"}" failed to generate after 2 attempts: ${
          lastError instanceof Error ? lastError.message : String(lastError)
        }`,
      ],
    });
  });

  try {
    await redis.set(cacheKey(blogInputId), JSON.stringify(newCache), "EX", CACHE_TTL_SECONDS);
  } catch (error) {
    log.warn("Section cache write failed (non-fatal)", { error: error instanceof Error ? error.message : String(error) });
  }

  return { drafts, usage, models: Array.from(models) };
}

/* ------------------------------------------------------------------ */
/* Repair helpers (targeted splice)                                    */
/* ------------------------------------------------------------------ */

export type ParsedSection = { heading: string | null; body: string };

/**
 * Split an article into (preamble incl. H1 + intro) + H2-keyed sections,
 * preserving order. The preamble entry has heading null.
 */
export function splitIntoSections(markdown: string): ParsedSection[] {
  const lines = markdown.split("\n");
  const sections: ParsedSection[] = [];
  let current: ParsedSection = { heading: null, body: "" };

  for (const line of lines) {
    if (line.startsWith("## ")) {
      sections.push(current);
      current = { heading: line.replace(/^##\s+/, "").trim(), body: `${line}\n` };
    } else {
      current.body += `${line}\n`;
    }
  }
  sections.push(current);
  return sections.filter((section) => section.heading !== null || section.body.trim().length > 0);
}

export function joinSections(sections: ParsedSection[]): string {
  return sections
    .map((section) => section.body.trim())
    .filter(Boolean)
    .join("\n\n")
    .trim();
}

/** Case/format-insensitive H2 lookup for judge-provided section names. */
export function findSection(sections: ParsedSection[], heading: string): ParsedSection | undefined {
  const wanted = normalizeHeading(heading);
  return sections.find((section) => {
    if (section.heading === null) return false;
    const have = normalizeHeading(section.heading);
    return have === wanted || have.includes(wanted) || wanted.includes(have);
  });
}
