import { createHash } from "crypto";
import { env, isVertexConfigured } from "../shared/env";
import { generateVertexText } from "../shared/vertex";
import { getSetting, MODEL_SETTING_KEYS } from "../shared/settings";
import { logger } from "../shared/logger";
import { redis } from "../shared/redis";
import { QualityGateError } from "../shared/recovery";
import type { GroundedSource } from "./citations";

const log = logger.child({ worker: "writing-worker", stage: "sections" });

/**
 * Section-by-section writing (ENHANCEMENT_IMPLEMENTATION_PLAN.md Task 5).
 * Instead of one monolithic 8k-token completion (which degrades
 * mid-document and must be wholly regenerated on any QA failure), the
 * article is decomposed into the mandatory section skeleton, each section
 * generated by an independent Flash-class call, retried individually, and
 * cached in Redis so a stage-level retry only regenerates what failed.
 *
 * The section plan derives from the MANDATORY skeleton (not the outline's
 * free-form sections) so sectioned output is structurally guaranteed to
 * satisfy the writing gate and the quality scorer's requiredSections -
 * outline bullets/FAQs are merged in where they align.
 */

export type SectionKind =
  | "intro"
  | "toc"
  | "generic"
  | "subsections"
  | "steps"
  | "table"
  | "numbered"
  | "bullets"
  | "faq"
  | "cta";

export type SectionSpec = {
  /** H2 text; null only for the heading-less intro. */
  heading: string | null;
  kind: SectionKind;
  intent: string;
  bullets: string[];
  wordTarget: number;
};

export type SectionArticleContext = {
  title: string;
  topic: string;
  description: string;
  plan?: {
    searchIntent: string;
    audience: string;
    angle: string;
    primaryKeyword: string;
    secondaryKeywords: unknown;
    competitorNotes: unknown;
  };
  outline?: { sections: unknown; faqs: unknown };
  sources?: GroundedSource[];
  keywords: string[];
};

export type SectionDraft = {
  heading: string | null;
  markdown: string;
  usage: { promptTokens: number; completionTokens: number };
  model: string;
  fromCache: boolean;
};

type OutlineSectionLike = { heading?: unknown; intent?: unknown; bullets?: unknown; wordTarget?: unknown };
type OutlineFaqLike = { question?: unknown; answerIntent?: unknown };

/* ------------------------------------------------------------------ */
/* Section plan                                                        */
/* ------------------------------------------------------------------ */

/**
 * The mandatory skeleton scaled so word targets sum inside
 * BLOG_MIN_WORDS..BLOG_MAX_WORDS. Intro is a heading-less pseudo-section.
 */
function skeletonWords(total: number) {
  const weights: [string | null, SectionKind, number][] = [
    [null, "intro", 0.09],
    ["Table of Contents", "toc", 0.03],
    ["What is {topic}?", "generic", 0.09],
    ["Why it matters", "generic", 0.07],
    ["Key Features", "subsections", 0.11],
    ["Benefits", "subsections", 0.08],
    ["How it Works", "steps", 0.13],
    ["Real World Use Cases", "subsections", 0.1],
    ["Pros and Cons", "table", 0.08],
    ["Best Practices", "numbered", 0.08],
    ["Common Mistakes", "bullets", 0.07],
    ["FAQs", "faq", 0.1],
    ["Conclusion", "generic", 0.05],
    ["Call To Action", "cta", 0.02],
  ];
  return weights.map(([heading, kind, share]) => ({
    heading,
    kind,
    wordTarget: Math.max(40, Math.round(total * share)),
  }));
}

const DEFAULT_INTENTS: Record<SectionKind, string> = {
  intro: "Explain the topic, the reader's problem, and the practical value of reading on.",
  toc: "Linked table of contents for the article.",
  generic: "Cover the section topic with practical, specific detail.",
  subsections: "Break the topic into 2-4 named H3 subsections, each with a useful paragraph.",
  steps: "Explain the mechanism as 3-4 named H3 steps.",
  table: "Balanced pros/cons as a Markdown comparison table plus a short framing paragraph.",
  numbered: "Actionable numbered checklist.",
  bullets: "Common pitfalls as a bullet list with avoidance guidance.",
  faq: "4-6 H3 questions with concise, direct answers.",
  cta: "One short practical call-to-action paragraph related to DevKit Market.",
};

function normalizeHeading(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9 ]/g, "").trim();
}

/**
 * Build the section plan: mandatory skeleton + outline enrichment. An
 * outline section merges into a skeleton entry when its heading
 * fuzzy-matches (normalized substring in either direction); its bullets,
 * intent and wordTarget then steer that section's generation.
 */
export function buildSectionPlan(context: SectionArticleContext): SectionSpec[] {
  const targetTotal = Math.round((env.BLOG_MIN_WORDS + env.BLOG_MAX_WORDS) / 2);
  const skeleton = skeletonWords(targetTotal);

  const outlineSections: OutlineSectionLike[] = Array.isArray(context.outline?.sections)
    ? (context.outline.sections as OutlineSectionLike[])
    : [];
  const outlineFaqs: OutlineFaqLike[] = Array.isArray(context.outline?.faqs) ? (context.outline.faqs as OutlineFaqLike[]) : [];

  return skeleton.map(({ heading, kind, wordTarget }) => {
    const resolvedHeading = heading?.replace("{topic}", context.topic) ?? null;
    const match =
      resolvedHeading !== null
        ? outlineSections.find((section) => {
            if (typeof section.heading !== "string") return false;
            const a = normalizeHeading(section.heading);
            const b = normalizeHeading(resolvedHeading);
            return a.includes(b) || b.includes(a);
          })
        : undefined;

    let intent = typeof match?.intent === "string" && match.intent ? match.intent : DEFAULT_INTENTS[kind];
    let bullets = Array.isArray(match?.bullets) ? match.bullets.map(String).filter(Boolean) : [];
    if (kind === "faq" && outlineFaqs.length > 0) {
      const faqBullets = outlineFaqs
        .map((faq) =>
          typeof faq.question === "string"
            ? `${faq.question}${typeof faq.answerIntent === "string" ? ` - ${faq.answerIntent}` : ""}`
            : null
        )
        .filter((bullet): bullet is string => Boolean(bullet));
      if (faqBullets.length > 0) bullets = faqBullets;
      intent = "Answer these reader questions concisely (one H3 per question).";
    }
    const outlineWordTarget = typeof match?.wordTarget === "number" && match.wordTarget > 0 ? match.wordTarget : undefined;

    return {
      heading: resolvedHeading,
      kind,
      intent,
      bullets,
      wordTarget: outlineWordTarget ?? wordTarget,
    };
  });
}

/* ------------------------------------------------------------------ */
/* Section generation                                                  */
/* ------------------------------------------------------------------ */

function sectionTemperature(kind: SectionKind): number {
  if (kind === "steps" || kind === "table" || kind === "faq") return 0.25;
  if (kind === "intro" || kind === "generic") return 0.45;
  return 0.35;
}

function kindInstruction(kind: SectionKind, heading: string | null): string {
  switch (kind) {
    case "intro":
      return "Write the article introduction (2-4 paragraphs). No heading - start directly with prose.";
    case "generic":
      return `Start with exactly "## ${heading}" on its own line, then prose.`;
    case "subsections":
      return `Start with "## ${heading}", then 2-4 "### " subsections each with at least one useful paragraph.`;
    case "steps":
      return `Start with "## ${heading}", then 3-4 "### Step N: Name" subsections explaining the mechanism.`;
    case "table":
      return `Start with "## ${heading}", one short framing paragraph, then a Markdown comparison table (| columns |).`;
    case "numbered":
      return `Start with "## ${heading}", then a numbered list ("1. ", "2. ") of actionable practices, each with a sentence of detail.`;
    case "bullets":
      return `Start with "## ${heading}", then a bullet list ("- " only, never "* ") of mistakes with avoidance guidance.`;
    case "faq":
      return `Start with "## FAQs", then 4-6 "### " questions, each answered concisely in 1-2 short paragraphs.`;
    case "cta":
      return `Start with "## Call To Action", then one short practical CTA paragraph.`;
    default:
      return "";
  }
}

function buildSectionPrompt(spec: SectionSpec, context: SectionArticleContext, repairNote?: string): string {
  const sources = context.sources ?? [];
  const sourcesBlock =
    sources.length > 0
      ? `
SOURCES (ground truth for any specific fact - cite with markers, never URLs):
${sources.map((source) => `${source.marker} ${source.title}\n    "${source.excerpt}"`).join("\n")}
Marker rules: every number, percentage, date, version, or benchmark you write MUST end with its source marker (e.g. [S1]). Only ${sources.map((s) => s.marker).join(", ")} exist - never invent markers. If no source covers a specific, write it qualitatively instead of inventing a figure. When the SOURCES are thin on the subject's actual product/mechanics, write this section about the general category/technology instead of presenting invented specifics as confirmed facts about the named subject. Vagueness on uncovered specifics is fine; invented precision is not.`
      : "";

  const keywordsBlock = context.keywords.length > 0 ? `\nWeave in these keywords if natural to THIS section (never force): ${context.keywords.join(", ")}.` : "";
  const bulletsBlock = spec.bullets.length > 0 ? `\nCover these points:\n${spec.bullets.map((bullet) => `- ${bullet}`).join("\n")}` : "";
  const repairBlock = repairNote ? `\n${repairNote}\nRewrite the section so the issue is fixed while keeping anything that already worked.` : "";

  return `You are a Staff Technical Writer for DevKit Market, a developer-focused tech blog. You are writing ONE SECTION of a larger article - not the whole article.

Article title: "${context.title}"
Topic: "${context.topic}"
${context.plan ? `Audience: ${context.plan.audience}\nAngle: ${context.plan.angle}` : `Context: ${context.description || "none"}`}

Section to write: ${spec.heading ? `"## ${spec.heading}"` : "the introduction"}
Section intent: ${spec.intent}
Target length: ~${spec.wordTarget} words. Paragraphs under 100 words each; sentences average 15-20 words.
${kindInstruction(spec.kind, spec.heading)}${bulletsBlock}${keywordsBlock}${sourcesBlock}${repairBlock}

Rules: GitHub Flavored Markdown. Technical, practical, zero fluff. Output ONLY this section's Markdown - no H1, no article title, no commentary, no code fence around the whole section.`;
}

export type GenerateSectionOptions = {
  repairNote?: string;
  modelOverride?: string;
};

/** One section = one Flash-class call. Callers handle retry/caching. */
export async function generateSection(
  spec: SectionSpec,
  context: SectionArticleContext,
  options: GenerateSectionOptions = {}
): Promise<SectionDraft> {
  if (!isVertexConfigured) throw new Error("Vertex AI is not configured");
  const model = options.modelOverride ?? (await getSetting(MODEL_SETTING_KEYS.writingSections, env.VERTEX_FLASH));
  const result = await generateVertexText(model, buildSectionPrompt(spec, context, options.repairNote), {
    maxOutputTokens: Math.max(800, Math.ceil(spec.wordTarget * 2.5)),
    temperature: sectionTemperature(spec.kind),
    timeoutMs: env.WRITING_TIMEOUT_MS,
  });
  return {
    heading: spec.heading,
    markdown: result.text.trim(),
    usage: result.usage,
    model,
    fromCache: false,
  };
}

/* ------------------------------------------------------------------ */
/* Deterministic sections (no model call)                              */
/* ------------------------------------------------------------------ */

function anchorFor(heading: string): string {
  return `#${heading.toLowerCase().replace(/[^a-z0-9\s-]/g, "").replace(/\s+/g, "-")}`;
}

/** The ToC is pure structure - generating it with a model is wasted tokens. */
export function buildTableOfContents(plan: SectionSpec[]): SectionDraft {
  const links = plan
    .filter((spec): spec is SectionSpec & { heading: string } => spec.heading !== null && spec.kind !== "toc")
    .map((spec) => `- [${spec.heading}](${anchorFor(spec.heading)})`)
    .join("\n");
  return {
    heading: "Table of Contents",
    markdown: `## Table of Contents\n\n${links}`,
    usage: { promptTokens: 0, completionTokens: 0 },
    model: "local",
    fromCache: false,
  };
}

/* ------------------------------------------------------------------ */
/* Parallel execution + retry + Redis cache                            */
/* ------------------------------------------------------------------ */

async function mapWithConcurrency<T, R>(items: T[], concurrency: number, fn: (item: T) => Promise<R>): Promise<R[]> {
  const results: R[] = new Array(items.length);
  let cursor = 0;
  async function next(): Promise<void> {
    const index = cursor;
    cursor += 1;
    if (index >= items.length) return;
    results[index] = await fn(items[index]);
    return next();
  }
  await Promise.all(Array.from({ length: Math.min(concurrency, items.length) }, next));
  return results;
}

function cacheKey(trendId: string): string {
  return `sections:${trendId}`;
}

/** Inputs that must match for a cached section to be reused on retry. */
function inputsHash(plan: SectionSpec[], context: SectionArticleContext): string {
  return createHash("sha256")
    .update(
      JSON.stringify({
        headings: plan.map((spec) => spec.heading),
        title: context.title,
        sources: (context.sources ?? []).map((source) => source.marker),
        min: env.BLOG_MIN_WORDS,
        max: env.BLOG_MAX_WORDS,
      })
    )
    .digest("hex")
    .slice(0, 16);
}

type CachedSections = { inputsHash: string; sections: Record<string, { markdown: string; model: string }> };

const CACHE_TTL_SECONDS = 3600;

/**
 * Generate every model-backed section of the plan with bounded parallelism,
 * one in-call retry per section, and a 1h Redis cache keyed on the section
 * inputs - a BullMQ retry of the whole stage then only regenerates the
 * sections that failed, instead of paying for a full redraft.
 */
export async function generateAllSections(
  plan: SectionSpec[],
  context: SectionArticleContext,
  trendId: string
): Promise<{ drafts: SectionDraft[]; usage: { promptTokens: number; completionTokens: number }; models: string[] }> {
  const hash = inputsHash(plan, context);
  let cached: CachedSections | null = null;
  try {
    const raw = await redis.get(cacheKey(trendId));
    if (raw) {
      const parsed = JSON.parse(raw) as CachedSections;
      if (parsed.inputsHash === hash) cached = parsed;
    }
  } catch (error) {
    log.warn("Section cache read failed, generating uncached", { error: error instanceof Error ? error.message : String(error) });
  }

  const usage = { promptTokens: 0, completionTokens: 0 };
  const models = new Set<string>();
  const newCache: CachedSections = { inputsHash: hash, sections: {} };

  const drafts = await mapWithConcurrency(plan, env.WRITING_SECTION_CONCURRENCY, async (spec): Promise<SectionDraft> => {
    if (spec.kind === "toc") return buildTableOfContents(plan);

    const cacheId = spec.heading ?? "__intro__";
    const hit = cached?.sections[cacheId];
    if (hit) {
      models.add(hit.model);
      return { heading: spec.heading, markdown: hit.markdown, usage: { promptTokens: 0, completionTokens: 0 }, model: hit.model, fromCache: true };
    }

    let lastError: unknown;
    for (let attempt = 1; attempt <= 2; attempt += 1) {
      try {
        const draft = await generateSection(spec, context);
        usage.promptTokens += draft.usage.promptTokens;
        usage.completionTokens += draft.usage.completionTokens;
        models.add(draft.model);
        newCache.sections[cacheId] = { markdown: draft.markdown, model: draft.model };
        return draft;
      } catch (error) {
        lastError = error;
        log.warn(`Section "${spec.heading ?? "intro"}" generation attempt ${attempt} failed`, {
          error: error instanceof Error ? error.message : String(error),
        });
      }
    }
    throw new QualityGateError({
      stage: "writing-worker",
      score: 0,
      passed: false,
      reasons: [
        `Section "${spec.heading ?? "Introduction"}" failed to generate after 2 attempts: ${
          lastError instanceof Error ? lastError.message : String(lastError)
        }`,
      ],
    });
  });

  try {
    await redis.set(cacheKey(trendId), JSON.stringify(newCache), "EX", CACHE_TTL_SECONDS);
  } catch (error) {
    log.warn("Section cache write failed (non-fatal)", { error: error instanceof Error ? error.message : String(error) });
  }

  return { drafts, usage, models: Array.from(models) };
}

/* ------------------------------------------------------------------ */
/* Repair helpers (targeted splice)                                    */
/* ------------------------------------------------------------------ */

export type ParsedSection = { heading: string | null; body: string };

/**
 * Split an article into (preamble incl. H1 + intro) + H2-keyed sections,
 * preserving order. The preamble entry has heading null.
 */
export function splitIntoSections(markdown: string): ParsedSection[] {
  const lines = markdown.split("\n");
  const sections: ParsedSection[] = [];
  let current: ParsedSection = { heading: null, body: "" };

  for (const line of lines) {
    if (line.startsWith("## ")) {
      sections.push(current);
      current = { heading: line.replace(/^##\s+/, "").trim(), body: `${line}\n` };
    } else {
      current.body += `${line}\n`;
    }
  }
  sections.push(current);
  return sections.filter((section) => section.heading !== null || section.body.trim().length > 0);
}

export function joinSections(sections: ParsedSection[]): string {
  return sections
    .map((section) => section.body.trim())
    .filter(Boolean)
    .join("\n\n")
    .trim();
}

/** Case/format-insensitive H2 lookup for judge-provided section names. */
export function findSection(sections: ParsedSection[], heading: string): ParsedSection | undefined {
  const wanted = normalizeHeading(heading);
  return sections.find((section) => {
    if (section.heading === null) return false;
    const have = normalizeHeading(section.heading);
    return have === wanted || have.includes(wanted) || wanted.includes(have);
  });
}
