import { VertexAI } from "@google-cloud/vertexai";
import { env, isVertexConfigured } from "../shared/env";
import { logger } from "../shared/logger";

const log = logger.child({ worker: "writing-worker" });

export type BlogDraft = {
  title: string;
  slug: string;
  excerpt: string;
  metaTitle: string;
  metaDescription: string;
  keywords: string[];
  markdown: string;
  usage: { promptTokens: number; completionTokens: number };
};

function slugify(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
    .slice(0, 80);
}

function buildPrompt(topic: string, description: string): string {
  // Blueprint adapted from prompts/04-writing-worker-prompt.md, collapsed
  // into a single planning+writing pass since the planning/outline
  // workers aren't built yet (MVP scope).
  return `You are a Staff Technical Writer for DevKit Market, a developer-focused tech blog.

Write a ${env.BLOG_MIN_WORDS}-${env.BLOG_MAX_WORDS} word technical blog post about: "${topic}"
Context: ${description || "No additional context provided."}

Guidelines:
1. Tone: technical, practical, zero fluff.
2. Include at least one Markdown comparison table or code snippet where relevant.
3. Use proper GitHub Flavored Markdown (H2/H3 headings, lists, bold).
4. End with a short FAQ section and a one-paragraph conclusion.

Respond with ONLY a JSON object (no markdown code fences, no commentary) with these exact keys:
{
  "title": "SEO-friendly title, under 70 characters",
  "excerpt": "150-200 character summary",
  "metaTitle": "under 60 characters",
  "metaDescription": "under 160 characters",
  "keywords": ["3-6 lowercase keyword strings"],
  "markdown": "the full article body in GitHub Flavored Markdown"
}`;
}

/** Extracts a JSON object from a model response, tolerating ```json fences. */
function extractJson(text: string): any {
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/i);
  const candidate = fenced ? fenced[1] : text;
  return JSON.parse(candidate.trim());
}

let warnedMock = false;

async function generateMock(topic: string, description: string): Promise<BlogDraft> {
  if (!warnedMock) {
    log.warn(
      "GOOGLE_CLOUD_PROJECT / GOOGLE_APPLICATION_CREDENTIALS not set - using mock writer output. Set both in .env to call real Vertex AI."
    );
    warnedMock = true;
  }

  const title = `${topic}: What Developers Need to Know`;
  const markdown = `## Overview\n\n${topic} is trending today${
    description ? ` - ${description}` : ""
  }. This is placeholder content generated by the mock writer because Vertex AI credentials are not configured.\n\n## Why it matters\n\nOnce \`GOOGLE_CLOUD_PROJECT\` and \`GOOGLE_APPLICATION_CREDENTIALS\` are set in \`.env\`, this section will be replaced with a real ${env.BLOG_MIN_WORDS}-${env.BLOG_MAX_WORDS} word Gemini-generated article.\n\n## FAQ\n\n**Is this real content?** No - this is a mock draft confirming the pipeline (Google Trends -> Postgres -> Blog record) works end-to-end.\n\n## Conclusion\n\nConfigure Vertex AI credentials to generate real articles for this topic.`;

  return {
    title,
    slug: slugify(title),
    excerpt: `Mock draft for "${topic}" - configure Vertex AI credentials to generate real content.`,
    metaTitle: title.slice(0, 60),
    metaDescription: `Mock draft covering ${topic}.`.slice(0, 160),
    keywords: [topic.toLowerCase()],
    markdown,
    usage: { promptTokens: 0, completionTokens: 0 },
  };
}

async function generateWithVertex(topic: string, description: string): Promise<BlogDraft> {
  const vertex = new VertexAI({
    project: env.GOOGLE_CLOUD_PROJECT!,
    location: env.VERTEX_LOCATION,
  });
  const model = vertex.getGenerativeModel({ model: env.VERTEX_MODEL });

  const prompt = buildPrompt(topic, description);
  const result = await model.generateContent({
    contents: [{ role: "user", parts: [{ text: prompt }] }],
  });

  const text = result.response.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) throw new Error("Vertex AI returned no text in response");

  const parsed = extractJson(text);
  const usage = result.response.usageMetadata;

  const title = String(parsed.title ?? topic);
  return {
    title,
    slug: slugify(title),
    excerpt: String(parsed.excerpt ?? ""),
    metaTitle: String(parsed.metaTitle ?? title).slice(0, 60),
    metaDescription: String(parsed.metaDescription ?? "").slice(0, 160),
    keywords: Array.isArray(parsed.keywords) ? parsed.keywords.map(String) : [],
    markdown: String(parsed.markdown ?? ""),
    usage: {
      promptTokens: usage?.promptTokenCount ?? 0,
      completionTokens: usage?.candidatesTokenCount ?? 0,
    },
  };
}

export async function generateBlogDraft(topic: string, description: string): Promise<BlogDraft> {
  return isVertexConfigured ? generateWithVertex(topic, description) : generateMock(topic, description);
}
